const shell = (title: string, body: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Ambient practice</title><style>
body{margin:0;font:15px/1.6 system-ui;background:#f5f7f9;color:#233345}header{padding:20px 6%;background:#193346;color:white;display:flex;justify-content:space-between}header a{color:#c0ded9;margin-left:18px}main{max-width:1050px;margin:35px auto;padding:0 30px}.notice{background:#fff2ce;padding:12px 20px;border-radius:8px;font-size:13px}section{background:white;border:1px solid #d9e1e8;padding:25px;border-radius:12px;margin-top:22px}button,.button{background:#24594c;border:0;border-radius:6px;padding:10px 16px;color:white;font:inherit;cursor:pointer;text-decoration:none}a{color:#246e9a}label{display:block;margin:15px 0 5px}input,select{padding:11px;border:1px solid #bdcbd5;border-radius:5px;font:inherit;min-width:260px}table{width:100%;border-collapse:collapse}td,th{padding:14px;text-align:left;border-bottom:1px solid #e4e9ed}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:5px 25px}small{color:#657586}h1{font-size:28px}</style></head><body><header><strong>${title}</strong><nav><a href="/fixtures/netsuite">Ledger</a><a href="/fixtures/gmail">Mailbox</a><a href="/fixtures/vendors">Vendors</a></nav></header><main><p class="notice">LOCAL PRACTICE DATA · A deterministic fixture for testing browser tools. This is not connected to NetSuite, Gmail, or any real account.</p>${body}</main></body></html>`;
export const fixtures = {
  netsuite: () => shell('NetSuite sandbox practice', `<h1>Accounts payable</h1><section><h2>Recorded vendor bills</h2><table><thead><tr><th>Vendor</th><th>Invoice</th><th>Date</th><th>Amount</th></tr></thead><tbody><tr><td>Northstar Software</td><td>NS-1041</td><td>2026-09-02</td><td>USD 1,200.00</td></tr></tbody></table><p><button id="new-bill" onclick="document.getElementById('bill').hidden=false;this.hidden=true">Add New Bill</button></p></section><section id="bill" hidden><h2>Add New Bill</h2><form onsubmit="event.preventDefault();document.getElementById('saved').textContent='Practice form submitted by a human.'"><div class="formgrid"><div><label for="vendor">Vendor</label><input id="vendor" name="vendor" aria-label="Vendor"></div><div><label for="invoice">Invoice number</label><input id="invoice" name="invoice"></div><div><label for="date">Invoice date</label><input id="date" type="date"></div><div><label for="amount">Amount</label><input id="amount" type="text"></div><div><label for="currency">Currency</label><select id="currency"><option>USD</option><option>EUR</option></select></div><div><label for="memo">Memo</label><input id="memo"></div></div><p><button type="submit">Save bill</button> <small>The assistant must leave this button for you.</small></p><p id="saved"></p></form></section>`),
  gmail: (message?: string) => {
    const invoices: Record<string, { vendor: string; number: string; amount: string; note: string }> = {
      'ns1041': { vendor: 'Northstar Software', number: 'NS-1041', amount: '1,200.00', note: 'September software subscription. Invoice date 2026-09-02.' },
      'ns1042': { vendor: 'Northstar Software', number: 'NS-1042', amount: '850.00', note: 'Additional licenses. Invoice date 2026-09-08. Payment due 2026-10-08.' },
      'ac300': { vendor: 'Acorn Consulting', number: 'AC-300', amount: '2,400.00', note: 'September implementation consulting. Invoice date 2026-09-09.' },
    };
    const selected = message && invoices[message];
    return shell('Gmail practice', selected ? `<h1>Invoice ${selected.number} — ${selected.vendor}</h1><section><p>From: billing@example.test</p><p>Date: 2026-09-09</p><h2>${selected.vendor}</h2><p>Invoice number: ${selected.number}</p><p>Amount: USD ${selected.amount}</p><p>${selected.note}</p><p>Please find the invoice details above. Thank you.</p><a href="/fixtures/gmail">Back to inbox</a></section>` : `<h1>Inbox</h1><section><form role="search" onsubmit="event.preventDefault();const q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('[data-mail]').forEach(r=>r.hidden=!(q.includes('invoice')||r.textContent.toLowerCase().includes(q)));document.getElementById('scope').textContent='Search results in the three-message practice inbox.'"><label for="search">Search mail</label><input id="search" type="search" placeholder="Search mail"><button>Search</button></form><p id="scope">Three messages · September 2026</p><table><thead><tr><th>Sender</th><th>Subject</th><th>Date</th></tr></thead><tbody>${Object.entries(invoices).map(([id, item]) => `<tr data-mail><td>${item.vendor}</td><td><a href="/fixtures/gmail?message=${id}">Invoice ${item.number} — USD ${item.amount}</a></td><td>September 2026</td></tr>`).join('')}</tbody></table></section>`);
  },
  vendors: () => shell('Vendor register practice', '<h1>Onboarded vendors</h1><section><table><thead><tr><th>Vendor</th><th>Status</th><th>Currency</th></tr></thead><tbody><tr><td>Northstar Software</td><td>Onboarded</td><td>USD</td></tr></tbody></table><p>Only Northstar Software is listed in this practice register.</p></section>'),
};
